session_name: site
windows:
  - focus: 'true'
    layout: dd1d,225x76,0,0[225x57,0,0,1,225x18,0,58{112x18,0,58,2,112x18,113,58,3}]
    options: {}
    panes:
      - 
      - nix develop
      - focus: 'true'
    start_directory: /home/joseph/projects/site
    window_name: dev
  - window_name: shell
    panes:
      - nix develop --command task dev:frontend
