session_name: site
windows:
- focus: 'true'
  layout: bb9c,225x76,0,0[225x57,0,0,0,225x18,0,58,2]
  options: {}
  panes:
  - focus: 'true'
  - nix-shell
  start_directory: /home/joseph/projects/site
  window_name: dev
