# https://taskfile.dev

version: '3'

tasks:
  test:frontend:all:
    silent: true
    dir: frontend
    cmds:
      - |
        npm run test:links


  build:data:
    silent: true
    cmds:
      - if ! [ -d ./dist ]; then mkdir dist; fi
      - |
        cd tools/staticBuilder
        npm run build:posts
        npm run build:rss


  build:frontend:staging:
    silent: true
    dir: frontend
    cmds:
      - APP_ENV=staging npm run build


  build:frontend:production:
    silent: true
    dir: frontend
    cmds:
      - APP_ENV=production npm run build


  dev:frontend: 
    silent: true
    dir: frontend
    cmds:
      - npm run dev -- --host


  run:frontend:
    silent: true
    dir: frontend
    cmds:
      - vite preview


  deploy:data:staging:
    silent: true
    cmds:
      - rclone copyto dist/posts.json r2:flinnlab-blog-dev/posts.json
      - rclone copyto dist/rss.xml r2:flinnlab-blog-dev/rss.xml
      - rclone sync data/images/ r2:flinnlab-blog-images-dev


  deploy:data:production:
    silent: true
    dir: data
    cmds:
      #- rclone copyto posts.json r2:flinnlab-blog-dev/posts.json
      - rclone sync images/ r2:flinnlab-blog-images


  install:hooks:
    silent: true
    cmds:
      - rm -rf .git/hooks
      - ln -s $PWD/tools/git-hooks .git/hooks


  new:post:
    silent: true
    dir: ./
    cmds:
      - | 
        NEW_POST="wip-slug.md"
        if [[ -f "frontend/posts/$NEW_POST" ]]; then
          echo "[!] $NEWPOST already exists!"
        else
          cp ./tools/wip-template.md ./frontend/posts/$NEW_POST
          echo "[*] $NEW_POST created."
        fi
