# https://taskfile.dev

version: '3'

tasks:
  build:posts:
    silent: true
    dir: data
    cmds:
      - npm run build:posts

  build:rss:
    silent: true
    dir: data
    cmds:
      - npm run build:rss

  build:frontend:
    silent: true
    dir: frontend
    cmds:
      - npm run build

  run:frontend: 
    silent: true
    dir: frontend
    cmds:
      - npm run dev

  deploy:data:staging:
    silent: true
    dir: backend
    cmds:
      - wrangler r2 object put flinnlab-blog-dev/posts.json --file ../data/posts.json

  install:hooks:
    silent: true
    cmds:
      - rm -rf .git/hooks
      - ln -s $PWD/tools/git-hooks .git/hooks

  new:post:
    silent: true
    cmds:
      - |
        latest_post=$(ls {{.USER_WORKING_DIR}}/[0-9][0-9][0-9][0-9]* | sort | tail -n 1)
        latest_post_file=$(basename $latest_post)
        latest_post_id=$(echo "${latest_post_file:0:4}")
        next_id=$( printf "%04d" $((latest_post_id + 1)))

        cp {{.USER_WORKING_DIR}}/wip-template.md {{.USER_WORKING_DIR}}/$next_id-slug.md
