name = "blog"
main = "src/worker.js"
compatibility_date = "2023-08-01"

[vars]
FLAG_USE_HEADERS=true

[[r2_buckets]]
binding = "BLOG_BUCKET"
bucket_name = "flinnlab-blog"
preview_bucket_name = "flinnlab-blog-dev"
