name = "blog-backend"
main = "src/worker.js"
compatibility_date = "2023-08-01"

workers_dev = true
r2_buckets  = [
  { binding = "BLOG_BUCKET", bucket_name = "flinnlab-blog-dev", preview_bucket_name = "flinnlab-blog-dev"}
]

[vars]
FLAG_USE_HEADERS=true

[dev]
ip = "0.0.0.0"
local_protocol = "http"
port = 8787
upstream_protocol = "https"


[env.staging]
name = "blog-backend-dev"

workers_dev = true
r2_buckets  = [
  { binding = "BLOG_BUCKET", bucket_name = "flinnlab-blog-dev" }
]
d1_databases = [
  { binding = "DB", database_name = "blog-trickle-dev",  database_id = "b3e160c5-bcb4-4c1b-80d0-03d0c56bc8b9" }
]

[env.staging.vars]
FLAG_USE_HEADERS=true


[env.production]
name = "blog-backend"

workers_dev = true
r2_buckets  = [
  { binding = "BLOG_BUCKET", bucket_name = "flinnlab-blog" }
]

[env.production.vars]
FLAG_USE_HEADERS=true
