---
name: CI

on: 
  workflow_dispatch:
    inputs: {}
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Build Site
        run: |
          cd frontend
          npm ci
          echo "{}" > src/posts.json
          npm run build


  build-data:
    name: Build Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Build data
        working-directory: data
        run: |
          npm run build:posts
          npm run build:rss


  test-backend:
    name: Deploy & Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_KEY }}
          accountId: ${{ secrets.CF_ACCOUNT }}
          workingDirectory: backend
          command: deploy --env staging

      - name: Run Integration Tests
        uses: grafana/k6-action@2bd221c807b7cdbe4bb3abc6b3fa4d2da499fa9b #v0.3.0
        with:
          filename: backend/test/script.js
