name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    #- cron: '0 * * * *'   # Every Hour
    - cron: '0 15 * * *'   # Once a day at 7AM PST

jobs:
  merge_schedule:
    runs-on: ubuntu-2022
    steps:
      - uses: gr2m/merge-schedule-action@b00191bec092ae480b63bf466fb94b5474b71cdd  # v2.4.3
        with:
          merge_method: squash
          time_zone: 'America/Los_Angeles'
          require_statuses_success: 'true'
          automerge_fail_label: 'merge-schedule-failed'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
